# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-short:
  en: CSSA
  fr: AÉI
title-long:
  en: Computer Science Student Association
  fr: Association des Étudiants en Informatique
email: exec@cssa-aei.ca
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "/cssa-web" # the subpath of your site, e.g. /blog
url: "https://cssa-aei.github.io/cssa-web/" # the base hostname & protocol for your site
twitter_username: CSSAAEI
github_username:  CSSA-AEI

# Build settings
markdown: kramdown

#header messages
header-title:
  en: Computer Science<br>Student Association
  fr: Association des<br>Étudiants en Informatique
school-name:
  en: University of Ottawa
  fr: Université d'Ottawa
