# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

collections:
  events:
    output: true
  opportunities:
    output: true

# Site settings
title-short:
  en: CSSA
  fr: AÉI
title-long:
  en: Computer Science Student Association
  fr: Association des Étudiants en Informatique
email: exec@cssa-aei.ca
description:
  en: We, the Computer Science Student Association (CSSA) of the University of Ottawa, provide by this Constitution an organization dedicated to the pursuit of obtaining and managing resources for all members of the undergraduate Computer Science community at the University of Ottawa.
  fr: Nous nous appellons l’Association d’étudiants en Informatique (AÉI) de l’Université d’Ottawa. Gouverné par la constitution de l’université, nous sommes responsables pour la gestion de tout les resources disponsibles pour les membres de la programme baccaleauréate de l’université d’Ottawa en informatique.
index:
  en: index.html
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cssa-aei.ca" # the base hostname & protocol for your site
twitter_username: CSSAAEI
github_username:  CSSA-AEI
repository: CSSA-AEI/cssa-web

# Build settings
markdown: kramdown

#header messages
header-title:
  en: Computer Science<br>Student Association
  fr: Association des<br>Étudiants en Informatique
school-name:
  en: University of Ottawa
  fr: Université d'Ottawa
office: 
  en: Visit us in our office at SITE 4076
  fr: Rendez-nous visite à notre bureau au SITE 4076
upcoming-events:
  en: Upcoming Events
  fr: Évènements à Venir
latest-posts:
  en: Latest Posts
  fr: Derniers Messages
more-button:
  en: See more posts
  fr: Voir plus de posts
blog-url:
  en: /blog
  fr: /blog-fr
event-url:
  en: /events
  fr: /evenements


#Events
cost:
  en: Cost
  fr: Coût
location:
  en: Location
  fr: Emplacement
associations:
  en: 
  fr: 
facebook-link:
  en: Link
  fr: Lien
event-more-button:
  en: See more events
  fr: Voir plus d'événements

# Opportunities
new-opportunities:
  en: Opportunities
  fr: Opportunités
opportunities-url:
  en: /opportunities
  fr: /opportunites
opportunities-more-button:
  en: See more opportunities
  fr: Voir plus d'opportunités