name: Deploy to Cloudflare Pages

on:
    push:
        branches:
            - React-version-cssa-web

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            # Building
            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                node-version: 20
            
            - name: Install Dependencies
              working-directory: ./
              run: npm install

            - name: Build Site
              working-directory: ./
              run: npm run build
            
            # Send to Cloudflare
            - name: Publish to Cloudflare Pages
              uses: cloudflare/wrangler-action@v4
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                command: pages deploy ./build --project-name=cssa-website --branch=React-version-cssa-web
                gitHubToken: ${{ secrets.GITHUB_TOKEN }}