name: Deploy to Cloudflare Pages

on:
    push:
        branches:
            - React-version-cssa-web

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            # Building
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            
            - name: Install Dependencies
              run: npm install

            - name: Build Site
              run: npm run build
            
            # Send to Cloudflare
            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                projectName: cssa-website
                directory: dist
                gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                branch: React-version-cssa-web